language: php
php: 7.0
addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
env:
  global:
  # HP4T_ROLLBAR_DEPLOY_KEY
  - secure: ""
  # HEROKU_API_KEY
  - secure: ""
cache:
  apt: true
  directories:
  - vendor
  - node_modules
before_install:
- composer self-update
- nvm install stable
install:
- composer install
before_script:
- composer test
- npm install
- alias hp4t="$(npm bin)/hp4t"
- hp4t init
- hp4t provision stage
- hp4t deploy stage
- hp4t provision production
- hp4t promote stage
script:
- /bin/true
after_success:
- hp4t notify-rollbar
